# Internal DNS configuration

# Resolve lab domain
address=/web.lab/192.168.254.131

# Upstream DNS
server=8.8.8.8

# Listen on router interfaces
listen-address=127.0.0.1,192.168.247.50,192.168.254.131
