# firewalld Configuration

## Enable NAT (Masquerading)

firewall-cmd --zone=FedoraServer --add-masquerade --permanent
firewall-cmd --reload

---

## Allow DNS (DMZ zone)

firewall-cmd --zone=dmz --add-service=dns --permanent
firewall-cmd --reload

---

## Allow HTTP

firewall-cmd --add-service=http --permanent
firewall-cmd --reload

---

## DMZ → External Policy

firewall-cmd --permanent --new-policy=dmz-to-external
firewall-cmd --permanent --policy=dmz-to-external --add-ingress-zone=dmz
firewall-cmd --permanent --policy=dmz-to-external --add-egress-zone=FedoraServer
firewall-cmd --permanent --policy=dmz-to-external --set-target=ACCEPT
firewall-cmd --reload
