# Nginx reverse proxy with load balancing

http {

    upstream backend {
        server 192.168.10.50; # Web01 VLAN10
        server 192.168.20.50; # Web02 VLAN20
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
